# Regenerated by tools/build_apk.sh right before every export (from
# export_presets.cfg's version/name + version/code, plus the export
# timestamp) — never hand-edit VERSION/CODE/BUILT, they get overwritten.
class_name BuildInfo
extends RefCounted

const VERSION := "0.6.13"
const CODE := 23
const BUILT := "2026-07-04 05:09 UTC"
